import { UiDimention, UiElementItem } from "../types.slint";
import { NodeUtils, NodeSection, NodeBase } from "./node.slint";

export global ActionUtils {
    public pure function calculate-action-height(outcomes-count: int, inputs-count: int, outputs-count: int) -> length {
        return NodeUtils.calculate-node-height(3, outcomes-count + inputs-count + outputs-count);
    }

    public pure function calculate-outcome-y-offset(outcome-index: int) -> length {
        return NodeUtils.style-sheet.header-height + 
                NodeUtils.style-sheet.name-height + 
                NodeUtils.style-sheet.section-separator-height + 
                NodeUtils.style-sheet.section-header-height + 
                ((outcome-index + 1) * NodeUtils.style-sheet.item-height) - 
                NodeUtils.style-sheet.item-height / 2;
    }
}

export component Action inherits NodeBase {
    in property <string> name;

    title: "Action";
    subtitle: root.name;

    NodeSection {
        width: root.width;
        header: "Outcomes";
        items: root.outcomes;
    }

    NodeSection {
        width: root.width;
        header: "Inputs";
        items: root.inputs;
    }

    NodeSection {
        width: root.width;
        header: "Outputs";
        items: root.outputs;
    }
}
