import { UiDimention, UiElementItem } from "../types.slint";
import { VerticalBox } from "std-widgets.slint";

component ActionSection {
    in property <string> header;
    in property <[UiElementItem]> items;

    VerticalLayout {
        
        HorizontalLayout {
            padding-left: 5px;
            padding-right: 5px;
            Path {
                height: 20px;
                stroke: #c5c5c5;
                stroke-width: 1px;
    
                MoveTo {
                    x: 0;
                    y: 0;
                }
    
                LineTo {
                    x: 100;
                    y: 0;
                }
            }
        }

        Rectangle {
            height: 20px;
            background: #ffffff;            
    
            VerticalLayout {
                VerticalBox {
                    height: parent.height;
                    Text {
                        text: root.header;
                        color: #222222;
                        font-size: 12px;
                        font-weight: 600;
                        vertical-alignment: top;
                        horizontal-alignment: left;
                    }
                }
            }
        }

        VerticalLayout {
            padding-left: 5px;
            for item in root.items: Rectangle {
                height: 20px;
                background: #ffffff;            
    
                VerticalBox {
                    height: parent.height;
                    Text {
                        text: item.simple_name;
                        color: #7c7c7c;
                        font-size: 12px;
                        font-weight: 600;
                        vertical-alignment: center;
                        horizontal-alignment: left;
                    }
                }
            }
        }

    }
}

export component Action {
    property <bool> moving;
    property <length> offset-x;
    property <length> offset-y;
    
    callback on-move(UiDimention);
    callback on-move-end(UiDimention);

    in property <string> name;
    in property <[UiElementItem]> outcomes;
    in property <[UiElementItem]> inputs;
    in property <[UiElementItem]> outputs;

    TouchArea {
        width: parent.width;
        height: parent.height;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                root.offset-x = self.mouse-x;
                root.offset-y = self.mouse-y;
                root.moving = true;
            } else if (event.kind == PointerEventKind.up) {
                root.moving = false;
                on-move-end({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }

        moved => {
            if (root.moving) {
                root.x = root.x + self.mouse-x - root.offset-x;
                root.y = root.y + self.mouse-y - root.offset-y;
                on-move({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }
    }

    // border
    Rectangle {
        background: white;
        border-color: #25d434;
        border-width: 1px;
        width: child.width + 2px;
        height: child.height + 2px;
    }

    child := VerticalLayout {
        padding-bottom: 10px;

        Rectangle {
            height: 20px;
            min-width: 200px;
            background: #25d434;
            border-radius: 2px;

            Text {
                text: "Action";
                color: white;
                font-size: 12px;
                font-weight: 600;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        Rectangle {
            height: 20px;

            Text {
                text: root.name;
                color: #222222;
                font-size: 12px;
                font-weight: 600;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        ActionSection {
            header: "Outcomes";
            items: root.outcomes;
        }

        ActionSection {
            header: "Inputs";
            items: root.inputs;
        }

        ActionSection {
            header: "Outputs";
            items: root.outputs;
        }
    }
    
}