import {UiDimention} from "../types.slint";

export component Action {
    property <bool> moving;
    property <length> offset-x;
    property <length> offset-y;
    
    callback on-move(UiDimention);
    callback on-move-end(UiDimention);

    in property <string> name;

    TouchArea {
        width: parent.width;
        height: parent.height;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                root.offset-x = self.mouse-x;
                root.offset-y = self.mouse-y;
                root.moving = true;
            } else if (event.kind == PointerEventKind.up) {
                root.moving = false;
                on-move-end({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }

        moved => {
            if (root.moving) {
                root.x = root.x + self.mouse-x - root.offset-x;
                root.y = root.y + self.mouse-y - root.offset-y;
                on-move({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }
    }

    background := Rectangle {
        background: green;
        border-color: #7c7c7c;
        border-width: 1px;
        width: child.width + 2px;
        height: child.height + 2px;
    }

    child := VerticalLayout {
        Rectangle {
            height: 20px;
            min-width: 200px;
            background: #25d434;
            border-radius: 2px;

            Text {
                text: root.name;
                color: white;
                font-size: 12px;
                font-weight: 600;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        Rectangle {
            height: 250px;
            background: #ffffff;
        }
    }
    
}