import {UiDimention} from "../types.slint";

export component MovableRectangle inherits Rectangle {
    property <bool> moving;
    property <length> offset-x;
    property <length> offset-y;

    callback on-move(UiDimention);
    callback on-move-end(UiDimention);

    TouchArea {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        pointer-event (event) => {
            if event.kind == PointerEventKind.down && event.button == PointerEventButton.left {
                root.offset-x = self.mouse-x;
                root.offset-y = self.mouse-y;
                root.moving = true;
            } else if event.kind == PointerEventKind.up {
                root.moving = false;
                on-move-end({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }
        moved => {
            if root.moving {
                root.x = root.x + self.mouse-x - root.offset-x;
                root.y = root.y + self.mouse-y - root.offset-y;
                on-move({
                    x: root.x,
                    y: root.y,
                    width: root.width,
                    height: root.height,
                });
            }
        }
    }
}