
export struct UiDimention {
    x: length,
    y: length,
    width: length,
    height: length,
}

export struct UiNodeData {
    id: string,
    label: string,
    x: length,
    y: length,
    width: length,
    height: length,
}

export struct UiEdgeData {
    id: string,
    source: string,
    target: string,
    source-dim: UiDimention,
    target-dim: UiDimention,
    source-index: int,
    target-index: int,
}


// -----------------------------

export enum UiElementType {
    Action,
    State
}

export struct UiElementItem {
    name: string,
    simple_name: string,
    unused: bool,
    required: bool,
}

export struct UiAction {
    id: string,
    name: string,
    x: length,
    y: length,
    outcomes: [UiElementItem],
    inputs: [UiElementItem],
    outputs: [UiElementItem],
}

export struct UiLink {
    id: string,
    source_type: UiElementType,
    source_id: string,
    source_index: int,
    target_type: UiElementType,
    target_id: string,
    target_index: int,
}