export struct UiDimention {
    x: length,
    y: length,
    width: length,
    height: length,
}

export enum UiNodeClass {
    Action,
    State
}

export struct UiSectionItem {
    name: string,
    simple_name: string,
    unused: bool,
    required: bool,
}

export struct UiNode {
    id: string,
    class: UiNodeClass,
    name: string,
    x: length,
    y: length,
    outcomes: [UiSectionItem],
    inputs: [UiSectionItem],
    outputs: [UiSectionItem],
}

export struct UiLink {
    id: string,
    source_type: UiNodeClass,
    source_id: string,
    source_index: int,
    source_outcome_index: int,
    target_type: UiNodeClass,
    target_id: string,
    target_index: int,
}