import { MovableRectangle, RectangleDimensions } from "./movable-rectangle.slint";
import { SingleSideWrapArrowEdge } from "./edge/edge.slint";

struct UiDimention {
    x: length,
    y: length,
    width: length,
    height: length,
}

struct UiNodeData {
    id: string,
    label: string,
    x: length,
    y: length,
    width: length,
    height: length,
    background: color,
}

struct UiEdgeData {
    id: string,
    source: string,
    target: string,
    source-dim: UiDimention,
    target-dim: UiDimention,
}

export global GraphState {
    in-out property <[UiNodeData]> nodes: [];
    in-out property <[UiEdgeData]> edges: [];

    callback update-node(UiNodeData);
    callback save();
}

export component SlintDemoWindow inherits Window {
    width: 800px;
    height: 600px;

    for node[i] in GraphState.nodes: MovableRectangle {
        x: node.x;
        y: node.y;
        width: node.width;
        height: node.height;
        background: node.background;

        Text {
            text: node.label;
            font-size: 20px;
        }

        on-change(dim) => {
            GraphState.update-node({
                id: node.id,
                label: node.label,
                x: dim.x,
                y: dim.y,
                width: dim.width,
                height: dim.height,
                background: node.background,
            });
            // GraphState.changed();
        }
    }

    for edge[j] in GraphState.edges: SingleSideWrapArrowEdge {
        from: {
            x: edge.source-dim.x,
            y: edge.source-dim.y,
            width: edge.source-dim.width,
            height: edge.source-dim.height,
        };
        to: {
            x: edge.target-dim.x,
            y: edge.target-dim.y,
            width: edge.target-dim.width,
            height: edge.target-dim.height,
        };
    }
}
